### ISSUE TITLE
Support more Framework versions

### ISSUE THREAD

**Issue by aquamoth** [mathtone/MIST#1]
Like you wrote yourself on [CodeReview](http://codereview.stackexchange.com/questions/129509/mist-auto-implemented-attribute-driven-net-notification-mechanism), it would be useful to support more frameworks than 4.6.1. 

My organization is stuck in FW 4.5.1 for now for example, but I would love to get this beauty inside as soon as possible. :)

I'm no expert on Nugets but it shouldn't be worse than just compiling it for the lowest framework it inherently supports and let the newer engines just run it?

**Comment by mathtone** [comment]
Hi aquamoth, No problem I'll set that up, run a few tests and update the nuget package with versions for a few additional frameworks.  I'll probably roll that out a little later tonight or tomorrow.

**Comment by mathtone** [comment]
I published a new NuGet package (v 1.2.0) targeting additional frameworks.  If I set this up right, it should cover frameworks 4.0-4.6+.  The unit tests passes and I ran a few tests, everything seems to be working.  Enjoy and thanks for your feedback, I hope you find it useful.

**Comment by mathtone** [comment]
The nuget package is still a bit problematic.

**Comment by mathtone** [comment]
The nuget package now supports multiple framework versions.  There are still some issues uninstalling & reinstalling.
