### ISSUE TITLE
Static property on notifier gives invalid program exception

### ISSUE THREAD

**Issue by mathtone** [mathtone/MIST#11]
Enabling notification on a static property creates an invalid program when it tries to make a call to the notify target when the notify target is an instance method.

**Comment by aquamoth** [comment]
Static properties with state are pretty stupid (in my opinion). 
Actively marking them with Notify when the NotifyTarget is an instance method is really stupid and should preferably cause a compiler error. At least write a warning for any marked static property.
In implicit mode I suggest simply ignoring static properties altogether.
Den 13 jul 2016 18:21 skrev mik3c notifications@github.com:Enabling notification on a static property creates an invalid program when it tries to make a call to the notify target when the notify target is an instance method.

**Comment by mathtone** [comment]
Yeah I think that sounds right, ignoring the static properties.  In one of
my programs I changed an instance property and made it static and started
receiving this error.  Suppressing notification for that property fixed
it.  Other than that everything has been working great.
