### ISSUE TITLE
Reworking MIST as a Fody Add-In

### ISSUE THREAD

**Issue by mathtone** [mathtone/MIST#13]
Thinking about using Fody to handle the implementation of the build task, Fody is an established system for handling this problem but then again I like the fact the MIST is extremely lightweight and "unobtrusive..."  Anyone have thoughts on that?

**Comment by dss539** [comment]
Personally, I like Fody quite a lot as a consumer, so I wouldn't hesitate to use it as a platform for your work.

Were you aware that there already exists an INotifyPropertyChanged IL weaver based on Fody? https://github.com/Fody/PropertyChanged

You might want browse their source for some ideas to borrow in MIST, or you might decide to take the best of MIST and integrate it into PropertyChanged.Fody

As you know, INotifyPropertyChanged IL weaving is essential to a clean WPF experience. I hope your entry into the space will lead to overall advancements.

**Comment by mathtone** [comment]
Thanks for the feedback.  I have seen Fody/PropertyChanged.  It does a fine job at convenient INPC implementation with some nice features and is much more widely used of course, but I like the ability with MIST to specify a "Notifier" target method (as opposed to injecting the call to the "PropertyChanged" event), I think this is a key difference between the two solutions.

**Comment by MeganKerr** [comment]
My concern with this is the license for Fody. While I don't mind supporting OSS occasionally, I don't like the idea of being forced into a Patreon subscription.

**Comment by mathtone** [comment]
I'm taking a different approach, I don't think it needs to reworked as a fody add-in.  I'm working on handling the nuget package install for .net Core applications but I've been busy.
