### ISSUE TITLE
dll version not updated

### ISSUE THREAD

**Issue by aquamoth** [mathtone/MIST#3]
It seems you are not updating neither the `AssemblyVersion` or the `AssemblyFileVersion` in `AssemblyInfo.cs`. This will give us hell when we try to upgrade an existing installed application as Windows Installer it will simply ignore the files that "havn't changed".

Please change so `AssemblyInfo.cs` correctly states the versions. `AssemblyVersion` to display in the project file and `AssemblyFileVersion` to work with msi-files.

As example, I get this in the project file:

```
<Reference Include="Mathtone.MIST, Version=1.0.5992.38980, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\packages\Mathtone.MIST.1.2.0\lib\net45\Mathtone.MIST.dll</HintPath>
  <Private>True</Private>
</Reference>
```

Also, if I look at the actual file `Mathtone.MIST.dll` inside the packages folder, it says it is of version `1.0.0.0`.

**Comment by mathtone** [comment]
I think I see what's going on here, I think somehow when testing updates to the NuGet package the Mathtone.MIST project ended up with an unnecessary reference to an older version of itself, I'll clean that up and put out a new package a little later, thanks.

**Comment by mathtone** [comment]
I added a new package, this one should sort out this problem as well as some issues I was having with the installation script.  If you run into any other problems let me know, I'll get them sorted out as quickly as I can.
